name: cobabps
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.12
  http: ^0.13.6
  html: ^0.15.4
  google_fonts: ^4.0.4
  video_player: ^2.7.0
  gallery_saver: ^2.3.2
  permission_handler: ^11.0.1
  flutter_widget_from_html: ^0.10.5
  flutter_html: ^3.0.0-beta.2
  html_unescape: ^2.0.0
  provider: ^6.1.4
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/1.png
    - assets/images/2.png
    - assets/images/3.png
    - assets/images/4.png
    - assets/images/grup1.png
    - assets/images/grup2.png
    - assets/images/grup3.png
    - assets/images/grup4.png
    - assets/images/next.png
    - assets/images/splash.png
    - assets/images/logo.png
    - assets/images/sitiga.png
    - assets/images/idn.png
    - assets/images/sitigalogonew.svg
    - assets/images/sitigalogonew.png
    - assets/images/ilustrasi_penduduk.png
    - assets/images/lainya_button.png
    - assets/images/instagram.png
    - assets/images/twitter.png
    - assets/images/facebook.png
    - assets/video/splash.mp4
    
